/*
** NOTE: This file is generated by Gulp and should not be edited directly!
** Any changes made directly to this file will be overwritten next time its asset group is processed by Gulp.
*/

/// <reference path="ievent.ts" />
var dsc;
(function (dsc) {
    var Event = (function () {
        function Event(title, start, end, url, allDay) {
            this.title = title;
            this.start = start;
            this.end = end;
            this.url = url;
            this.allDay = allDay;
        }
        return Event;
    })();
    dsc.Event = Event;
})(dsc || (dsc = {}));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIkV2ZW50LmpzIiwiRXZlbnQudHMiXSwibmFtZXMiOlsiZHNjIiwiZHNjLkV2ZW50IiwiZHNjLkV2ZW50LmNvbnN0cnVjdG9yIl0sIm1hcHBpbmdzIjoiQUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsQUNMQSxrQ0FBa0M7QUFFbEMsSUFBTyxHQUFHLENBVVQ7QUFWRCxXQUFPLEdBQUcsRUFBQyxDQUFDO0lBQ1JBO1FBQ0lDLGVBQ1dBLEtBQWFBLEVBQ2JBLEtBQWFBLEVBQ2JBLEdBQVdBLEVBQ1hBLEdBQVdBLEVBQ1hBLE1BQWVBO1lBSmZDLFVBQUtBLEdBQUxBLEtBQUtBLENBQVFBO1lBQ2JBLFVBQUtBLEdBQUxBLEtBQUtBLENBQVFBO1lBQ2JBLFFBQUdBLEdBQUhBLEdBQUdBLENBQVFBO1lBQ1hBLFFBQUdBLEdBQUhBLEdBQUdBLENBQVFBO1lBQ1hBLFdBQU1BLEdBQU5BLE1BQU1BLENBQVNBO1FBQzFCQSxDQUFDQTtRQUNMRCxZQUFDQTtJQUFEQSxDQVJBRCxBQVFDQyxJQUFBRDtJQVJZQSxTQUFLQSxRQVFqQkEsQ0FBQUE7QUFDTEEsQ0FBQ0EsRUFWTSxHQUFHLEtBQUgsR0FBRyxRQVVUIiwiZmlsZSI6IkV2ZW50LmpzIiwic291cmNlc0NvbnRlbnQiOltudWxsLCIvLy8gPHJlZmVyZW5jZSBwYXRoPVwiaWV2ZW50LnRzXCIgLz5cclxuXHJcbm1vZHVsZSBkc2Mge1xyXG4gICAgZXhwb3J0IGNsYXNzIEV2ZW50IGltcGxlbWVudHMgZHNjLklFdmVudCB7XHJcbiAgICAgICAgY29uc3RydWN0b3IoXHJcbiAgICAgICAgICAgIHB1YmxpYyB0aXRsZTogc3RyaW5nLFxyXG4gICAgICAgICAgICBwdWJsaWMgc3RhcnQ6IHN0cmluZyxcclxuICAgICAgICAgICAgcHVibGljIGVuZDogc3RyaW5nLFxyXG4gICAgICAgICAgICBwdWJsaWMgdXJsOiBzdHJpbmcsXHJcbiAgICAgICAgICAgIHB1YmxpYyBhbGxEYXk6IGJvb2xlYW4pIHtcclxuICAgICAgICB9XHJcbiAgICB9XHJcbn0iXSwic291cmNlUm9vdCI6Ii9zb3VyY2UvIn0=
